// Generated by Wrangler by running `wrangler types`

interface Env {
	REALTIME_TURN_TOKEN_TTL_SECONDS: number;
	REALTIME_TURN_TOKEN_ID: string;
	REALTIME_TURN_TOKEN_SECRET: string;
	REALTIME_TURN_ORIGINS: string;
}
