// Generated by Wrangler by running `wrangler types`

interface Env {
	CALLS_TURN_TOKEN_TTL_SECONDS: number;
	CALLS_TURN_TOKEN_ID: string;
	CALLS_TURN_TOKEN_SECRET: string;
	CALLS_TURN_ORIGINS: string;
}
